### ISSUE TITLE
LoliASM's onDemandAnimatedTextures feature seems to instead break all animated textures, due to Nothirium.

### ISSUE THREAD

**Issue by MagmaBro123** [Meldexun/Nothirium#75] opened 2023-07-22 17:14 UTC
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Title.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [X] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Use LoliASM and Nothirium together with onDemandAnimatedTextures enabled.

**Screenshots/Videos**
https://github.com/Meldexun/Nothirium/assets/51277766/e598bb3c-a851-4f23-961d-ae8238be0e7f
(Video won't embed. Blame GitHub.)

**Versions**
![image](https://github.com/Meldexun/Nothirium/assets/51277766/aa3b5624-d8b6-4315-bede-2babae84a054)

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 
**No idea how to get this info.**

**Log File**
N/A. I never saw anything in the logs about this.

**Comment by Meldexun** [comment] 2023-07-22 19:00
Duplicate of #65

**Closed by Meldexun** 2023-07-22 19:00 UTC
Labels: bug, unconfirmed
