### ISSUE TITLE
Nothirium conflict with Vanillafix

### ISSUE THREAD

**Issue by xXDarkNovaXx** [Meldexun/Nothirium#31] opened 2022-07-11 06:46 UTC
**Describe the bug**
Apparently there is a conflict between Nothirium and the Vanillafix mod, because when both mods are active, the ME controller animation no longer works. 
The animation is only updated when something changes in the network, e.g. when you remove an ME cable that is connected to a machine or something else, or when you plug a cable back in, or when you connect other ME controllers to the ME controller, because this updates the network
Deactivating Nothirium or Vanillafix it works fine again

Edit: It seems that this problem is related to the texture optimization feature of VanillaFix, because if you disable it, the animation works again.
I don't know why this is and what causes the conflict in this function.

**To Reproduce**
1. Have activated Nothirium and Vanillafix
2. Place a creative energy cell from Applied Energistics 
3. Place a ME controller on the energy cell
**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

Newly created Test Setup Mods:
Nothirium: 0.1.6
RenderLib: 1.1.0
Forge: 14.23.5.2860
Minecraft: 1.12.2
Applied Energistics2: rv6-stable-7
Entity Culling: 6.1.0
MixinBooter: 4.2
Optifine 1.12.2 HD U G5
VanillaFix 1.0.10-150

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:

**Comment by Meldexun** [comment] 2022-07-13 21:49
Duplicate of #24

**Closed** 2022-07-13 21:49 UTC
Labels: bug
