### ISSUE TITLE
LagGoggles incompatibility when installed along CTM and Farseek

### ISSUE THREAD

**Issue by Delfite** [Meldexun/Nothirium#51] opened 2023-02-06 11:23 UTC
### **Describe the bug**
I installed Nothirium along with RenderLib, Mixin 0.7-0.8 compatibility, and MixinBooter into the modpack "Epoch Runner" and the game crashed on launch with `Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderManager`

Usually an error like that means I'm missing something even though I installed all the right dependencies for Nothirium

### **Reproducibility**
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### **To Reproduce**
1. Download the modpack [Epoch Runner](https://www.curseforge.com/minecraft/modpacks/epoch-runner)
2. Enable content management for the profile
3. Install Nothirium and it's dependencies
4. Launch the game and the crash should happen

### **Screenshots/Videos**
None.

### **Versions**
Nothirium: Nothirium-1.12.2-0.1.10-beta.jar
RenderLib: RenderLib-1.12.2-1.1.10.jar
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Unsure.

### **Hardware**
CPU: Ryzen 5-2600 @ 3.4GHz
RAM: 2x8GB G.Skill Ripjaws
GPU: GTX 1660 SUPER
VRAM: VRAM literally just stands for "Video RAM", which is what the GPU is responsible for XD

### **Log File**
debug.log (less concise but far more detailed): https://mclo.gs/3N8dEmx
latest.log (more concise but far less detailed): https://mclo.gs/ZSEeSoB

**Comment by quentin452** [comment] 2023-02-06 11:36
try removing mixin 0.7 because mixinbooter already has it

**Comment by Meldexun** [comment] 2023-02-06 16:33
This looks like an incompatibility with another mod. It seems that another mod is also modifying the `RenderManager` class which causes my mixins to fail. Please test what other mod is causing the crash.

**Comment by SilverBeamx** [comment] 2023-06-21 22:53
Regarding this issue, i can confirm that LagGoggles, by themselves, aren't the issue. I have been running LagGoggles version 5.9-140 without any compatibility issues so far.

**Comment by Meldexun** [comment] 2023-07-02 11:44
Fixed in v1.12.2-0.3.1-beta

**Closed by Meldexun** 2023-07-02 11:44 UTC
Labels: bug, confirmed
