### ISSUE TITLE
Texture of the game is not displayed

### ISSUE THREAD

**Issue by EldraTheThird** [Meldexun/Nothirium#62] opened 2023-03-22 12:16 UTC
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
The texture of the game is not showing when I use this mod :/ it looks transparent

**Reproducibility**
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
I just installed some mods like OptiFine, Surge, Nothirium, RenderLib and Better Biome Blend. Then I use Feather Client Forge 1.12.2 to play. And when I enter the world or the server, it only shows the players/mobs but not the texture of the block :/

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/108326998/226900680-bc8febda-ba15-44e7-9592-f788865630b4.png)

**Versions**
Nothirium: 1.12.2-0.2.4-beta
RenderLib: 1.12.2-1.2.7
Forge: 14.23.5.2860
Minecraft: 1.12.2 
Other mods (necessary to reproduce the bug): 
OptiFine, Surge, Better Biome Blend and Feather Client Forge (it's a client but i think it should be added).
**Hardware**
CPU: Intel Pentium G4400
RAM: 4GB DDR4 2400MHz
GPU: Intel HD 510
VRAM: 2GB

**Log File**
[latest.log](https://github.com/Meldexun/Nothirium/files/11039828/latest.log)

**Comment by Meldexun** [comment] 2023-04-15 10:32
Duplicate of #25

**Closed by Meldexun** 2023-04-15 10:32 UTC
Labels: bug, unconfirmed
