### ISSUE TITLE
Surrounding texture becomes empty.

### ISSUE THREAD

**Issue by Droid-Hai** [Meldexun/Nothirium#20] opened 2022-06-04 10:21 UTC
**Describe the bug**
Just start game.

**To Reproduce**
Nothing.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/91696776/171993770-521c46f6-730d-461d-bc01-c9f63c06b7cc.png)

**Versions**
Nothirium: [0.1.4-beta](https://www.curseforge.com/minecraft/mc-mods/nothirium/files/3807990)
RenderLib: [1.0.7](https://www.curseforge.com/minecraft/mc-mods/renderlib/files/3807955)
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Nothing.

**Hardware**
CPU: 2x AMD Radeon A6-6420K
RAM: 4 GB
GPU: AMD Radeon HD 8470D
VRAM: Probably 1-2 GB

**Log File**
https://pastebin.com/bMdwnBA0

This is a duplicate - https://github.com/Meldexun/Nothirium/issues/10. It says that this is an incompatibility of the [fastutil](https://search.maven.org/artifact/it.unimi.dsi/fastutil) version. I have tested several recent versions but it has not yielded results.

**Comment by MineCinema** [comment] 2022-06-06 21:26
I observe the same problem with users who played on the assembly with this mod. Players also complain that only the NPC is visible, while nothing was found in the logs. What unites them is the client and the fact that they are sitting on weak computers. Pentium series processors and GT series video cards

**Comment by MineCinema** [comment] 2022-06-06 21:58
I observe a similar problem with players who played on the assembly with this mod. They complained that they only see NPCs. I read their logs and did not find anything with which there would be a conflict. Unites them just played quite on old PCs. GeForce Gt 220, Gt620 series video c
[latest (3).log](https://github.com/Meldexun/Nothirium/files/8848364/latest.3.log)
ard using the latest drivers.Players with newer components do not have any problems, only FPS prevarication/
[latest (2).log](https://github.com/Meldexun/Nothirium/files/8848363/latest.2.log)

**Comment by embeddedt** [comment] 2022-06-07 14:21
I have access to a very ancient PC with Intel GMA graphics (that support up to OpenGL 2) which I saw this issue on, so I can test it on Friday if no one else can before then.

**Comment by Droid-Hai** [comment] 2022-06-24 11:28
> [gltest.zip](https://github.com/Meldexun/Nothirium/files/8853702/gltest.zip) Someone who is able to reproduce the issue please launch minecraft with this mod installed and send the crash report.

Caused by: java.lang.RuntimeException: GL: 4.3 - 4.3
	at meldexun.gltest.GLTest.onFMLConstructionEvent(GLTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Meldexun** [comment] 2022-06-24 12:19
Please make sure your drivers are up to date and try to reproduce the issue with Nothirium-1.12.2-0.1.5-beta and RenderLib-1.12.2-1.0.8 and then send the log.

**Comment by Meldexun** [comment] 2022-08-08 19:23
Please update RenderLib to v1.12.2-1.1.3 and set the `enableGLDebug` config option from RenderLib to true. Then try to reproduce the issue and upload the log file (for example https://gist.github.com/).

**Comment by Meldexun** [comment] 2022-08-27 12:05
I think this is the same issue as #25 and because the newer issue seems to be more active I will close this now.

**Comment by Meldexun** [comment] 2022-08-27 12:05
Duplicate of #25

**Closed by Meldexun** 2022-08-27 12:05 UTC
Labels: bug, unconfirmed
