### ISSUE TITLE
Invisible entity blocks when used with valkyrien skies 

### ISSUE THREAD

**Issue by allforone33** [Meldexun/Nothirium#43] opened 2022-09-26 08:07 UTC
**Describe the bug**
Anytime you assemble a ship, the engines, the cables, the physics infuser, chests, any sort of block that's animated or an like an entity will be invisible when Nothirium is installed.

**Update** 
In the latest versions of the mod it seems that now everything is invisble, whether the ship is assembled or not. Chests, physics infusers all entityblocks it seems.

**Reproducibility**
You can simply reproduce the bug by having valkyrien skies and any version of this mod installed, along with renderlib and it will do the same thing as I described above. 

**To Reproduce**
1. install valkyrien skies
2. install nothirium and renderlib
3. Load the game and watch as the entityblocks such as the compressors disappear and chests are rendered invisible

**Screenshots/Videos**
![glitch](https://user-images.githubusercontent.com/112358552/192422046-e2163a4f-75ee-4194-bcff-8e81c6d4485b.png)

**Versions**
Nothirium: 0.7.10-beta-0.1.10 beta
RenderLib: 1.1.1-1.1.9
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):  valkyrien skies (the three mods that make it up)

**Comment by Meldexun** [comment] 2022-09-26 10:59
Please follow the issue template and provide the requested information

**Comment by allforone33** [comment] 2022-09-27 03:04
> Please follow the issue template and provide the requested information

Updated

**Comment by Meldexun** [comment] 2022-09-28 19:06
Can you also upload a log file?

**Comment by allforone33** [comment] 2022-09-29 23:18
> Can you also upload a log file?

I've recently realized that it is the mod tick dynamic that causes the total invisibility and that the latest version seems to sort of work with valkyrien skies, when you go into f5 mode or on the captains chair it seems the objects seem to flicker.

**Comment by Meldexun** [comment] 2022-11-12 01:51
I tested this again and it seems that when I'm riding a valkyrien skies ship all entities and tile entities become invisible **without** Nothirium, RenderLib or any other mod even being installed.

**Comment by Meldexun** [comment] 2023-03-03 00:47
In RenderLib 1.12.2-1.2.6 I disabled AABB caching for tile entities on Valkyrien Skies ships which is the only issue that I found caused by RenderLib/Nothirium. So I will close this now. If there still is an issue please create a new issue.

**Closed by Meldexun** 2023-03-03 00:47 UTC
Labels: bug, incompatibility, confirmed
