### ISSUE TITLE
Incompatibility with Java Eclipse OpenJ9 VM

### ISSUE THREAD

**Issue by TheAirBlow** [Meldexun/Nothirium#64] opened 2023-04-15 10:05 UTC
**Describe the bug**
Randomly decides to stop working and crashes the game each time I join any world or server

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.

**To Reproduce**
It's impossible to reproduce, it just... happens. From time to time. \
Changing video settings triggers it, moving too fast does too... idk.

**Screenshots/Videos**
Just sky blue screen (literally, nothing else)

**Versions**
Nothirium: 0.2.4-beta
RenderLib: 1.2.8
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Hardware**
CPU: AMD Ryzen 5 3550H
RAM: 8 GB DDR4
GPU: AMD Radeon RX 560X
VRAM: 4 GB GDDR5

**Log File**
https://mclo.gs/KeoWYBf

**Comment by TheAirBlow** [comment] 2023-04-15 10:07
Additional question: why are you asking for the CPU/RAM/etc. in the issue, if it's all stated in the logs? (and it's perfectly accurate)

**Comment by Meldexun** [comment] 2023-04-15 15:15
Can you try to reproduce the issue with this Nothirium version and send me the crash report which will contain additional information?
[Nothirium-1.12.2-0.2.4-beta-#64test.jar.zip](https://github.com/Meldexun/Nothirium/files/11239860/Nothirium-1.12.2-0.2.4-beta-.64test.jar.zip)

> Additional question: why are you asking for the CPU/RAM/etc. in the issue, if it's all stated in the logs? (and it's perfectly accurate)

Because this is only present in crash reports not in "normal" log files.

**Comment by TheAirBlow** [comment] 2023-04-15 17:27
> Can you try to reproduce the issue with this Nothirium version and send me the crash report which will contain additional information? [Nothirium-1.12.2-0.2.4-beta-#64test.jar.zip](https://github.com/Meldexun/Nothirium/files/11239860/Nothirium-1.12.2-0.2.4-beta-.64test.jar.zip)
> 
> > Additional question: why are you asking for the CPU/RAM/etc. in the issue, if it's all stated in the logs? (and it's perfectly accurate)
> 
> Because this is only present in crash reports not in "normal" log files.

I can't get it to reproduce /shrug
The modpack is latest Technological Journey, you may have some luck with changing mipmaps in OptiFine or any other video settings which do a full reload.
Also, don't logs also contain the crash log too? I've seen them in mine.

**Comment by Meldexun** [comment] 2023-05-31 19:48
After additional testing I was able to reproduce the issue more or less consistently. It seems that the issue is caused by the JVM you are using.
I reported the issue to the openj9 issue tracker and they will hopefully be able to fix this.

In the mean time please consider using a different JVM (for example https://adoptium.net/temurin/releases/?version=8) which should fix the issue for you as well.

**Comment by TheAirBlow** [comment] 2023-05-31 20:43
> After additional testing I was able to reproduce the issue more or less consistently. It seems that the issue is caused by the JVM you are using. I reported the issue to the openj9 issue tracker and they will hopefully be able to fix this.
> 
> In the mean time please consider using a different JVM (for example https://adoptium.net/temurin/releases/?version=8) which should fix the issue for you as well.

That's funny. I'm basically forced to use OpenJ9 at the moment, it smooths out GC lag spikes by a lot.
I'd rather wait to be honest. And also, not playing that modpack anymore, doing DJ2 right now.
And here I have to use the stupid OpenJDK with huge lag spikes because of Recurrent Complex.

**Comment by Meldexun** [comment] 2023-08-18 11:53
This should be fixed in Eclipse OpenJ9 v0.40.0

**Closed by Meldexun** 2023-08-18 11:53 UTC
Labels: bug, wontfix, incompatibility, confirmed
