### ISSUE TITLE
Chunks loaded but not visible

### ISSUE THREAD

**Issue by pohorg43** [Meldexun/Nothirium#49] opened 2023-01-02 15:21 UTC
**Describe the bug**
when entering the world, you can break blocks, particles are visible, but the blocks themselves are not visible. but entities are visible through invisible blocks. minecraft without mods, except for the ones necessary for nothirium to work.
opengldebugoutput = true

**To Reproduce**
1. Install nothirium mod
2. Start Minecraft
3. Load a world
4. See the invisible blocks

**Screenshots/Videos**
https://imgur.com/a/ZsYpLiK

**Versions**
Nothirium: 0.1.10
RenderLib: 0.1.10
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods: mixinbootstrap 1.1.0

**Hardware**
CPU: AMD Athlon(tm) II X2 220
RAM: 6 GB
GPU: Nvidia GTX 560
VRAM: 1GB

**Log File**
https://gist.github.com/pohorg43/6dd062fce312ee0be246dca78a9c4885

**Comment by quentin452** [comment] 2023-01-02 15:40
duplicate of #25

**Comment by Meldexun** [comment] 2023-02-28 02:51
Duplicate of #25

I'm closing this issue now. Please refer to the original issue if you want to see the progress on this issue or have additional information.

**Closed by Meldexun** 2023-02-28 02:51 UTC
Labels: bug, unconfirmed
