### ISSUE TITLE
Cutting down a palm tree from Dynamic Trees Biomes O' Plenty addon crashes the game

### ISSUE THREAD

**Issue by Gliese-832-c** [Meldexun/Nothirium#61] opened 2023-03-19 13:46 UTC
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

I have enabled said config option.

**Describe the bug**
When you cut down a palm tree from the addon that brings BOP compatibility to Dynamic Trees, either the game freezes, needing to be killed using task manager, or the screen turns the same color as the sky for a second or so and the game crashes. Of note is that the leaves of the palm tree are rendered gray, so even before cutting it down and it turning into an entity, it seems to have something strange going on.

**Reproducibility**
- [ ] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.
I have made a new instance of the game with only Nothirium, RenderLib, MixinBooter, DynamicTrees, DynamicTreesBOP, and Biomes O' Plenty. It works perfectly fine.

**To Reproduce**
Steps to reproduce the behavior.
1. Obtain a palm tree. Either by going to a tropical island biome, or just planting one. (Search for palm tree seed in JEI/creative inventory, then use bone meal on it to make it at least two blocks tall.)
2. Try to cut it down by just breaking a block in the tree. Usually (you can test this with another tree type like oak) this just turns the tree into an entity, makes it fall over, and drops some logs and sticks. But with palm trees it crashes the game as soon as you cut the tree down, making me think that it's the spawned entity that causes the issues.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
Nothirium: 0.2.4
RenderLib: 1.2.7
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Dynamic Trees, Dynamic Trees BOP, Biomes O' Plenty

**Hardware**
CPU: Ryzen 5 2600
RAM: 16GB DDR4
GPU: RX 570
VRAM: 8GB

**Log File**
https://gist.github.com/Gliese-832-c/376979cda1befdabafaff663f9daf6c6
Hopefully the log with the openGLDebugOutput enabled is enough to figure out what is happening because as explained above, it doesn't happen in a clean instance, and I don't know what could be causing it.

**Comment by Meldexun** [comment] 2023-04-15 10:26
Duplicate of https://github.com/Meldexun/RenderLib/issues/24

**Closed** 2023-04-15 10:26 UTC
Labels: bug, unconfirmed
