### ISSUE TITLE
Crash on joining world

### ISSUE THREAD

**Issue by TheAirBlow** [Meldexun/Nothirium#68] opened 2023-06-03 09:16 UTC
**Describe the bug**
The game crashes when I try to join an Enigmatica 2 Expert: Unofficial server with Nothirium. \
OptiFine is NOT the issue, as it worked fine with it in all other packs I've played so far.

**Reproducibility**
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Explained clearly enough in description.

**Versions**
Nothirium: 0.2.4-beta
RenderLib: 1.2.8
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Hardware**
CPU: AMD Ryzen 5 3550H
RAM: 8 GB DDR4
GPU: AMD Radeon RX 560X
VRAM: 4 GB GDDR5

**Log File**
https://mclo.gs/jFUvpFN

**Comment by TheAirBlow** [comment] 2023-06-03 09:17
As 0.2.4-beta has an OptiFine-related update, I'll downgrade one version and test if the crash persists.

**Comment by Meldexun** [comment] 2023-06-03 09:38
Duplicate of #64

**Closed by Meldexun** 2023-06-03 09:38 UTC
Labels: bug, unconfirmed

**Comment by TheAirBlow** [comment] 2023-06-03 14:32
> Duplicate of #64

Oh sorry. IDK how did it launch with recurrent complex though, so I assumed it is OpenJDK... Prism set it to J9 instead lmao
