### ISSUE TITLE
FPS reduction when working together with Thermal Foundation

### ISSUE THREAD

**Issue by ghost** [Meldexun/Nothirium#47] opened 2022-12-20 10:32 UTC
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
When I install Nothirium or Nothirium + Optifine I see great fps, but when I add Thermal Foundation the fps is more than halved.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Install Nothirium (or Nothirium + Optifine)
2. Install Thermal Foundation
3. See performance degradation

**Screenshots/Videos**
Optifine + Nothirium:
![](https://imageup.ru/img232/4124225/optifine-nothirium.png)

Added Thermal Foundation:
![](https://imageup.ru/img140/4124229/drop.png)

**Versions**
Nothirium: 0.1.10
RenderLib: 1.1.10
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
Optifine: HD U G5
Mixin Booter: 7.0
Code Chicken Lib: 3.2.3.358
CoFH Core: 4.6.6.1
CoFH World: 1.4.0.1
Redstone Flux: 2.1.1.1
Thermal Foundation: 2.6.7.1

**Hardware**
CPU: Intel Core i5 3230M
RAM: 8Gb
GPU: Intel HD Graphics 4000
VRAM: 1792Mb

**Log File**
[latest.log](https://gist.github.com/WantaSanchez/f4f5296fd52f06b115a22cf8a0f82435)

**Comment by Meldexun** [comment] 2023-02-28 03:39
I tested Nothirium and Thermal Foundation myself and I didn't see any difference in performance. This is likely some kind of problem with your system. I suspect that with both mods installed you might run low on memory. Maybe only allocating 2GB to Minecraft instead of 4GB fixes the issue because the other memory can then be used as direct memory.

**Comment by Meldexun** [comment] 2023-04-15 10:29
Have you tried installing Thermal Foundation without any other mods?

**Comment by AlexChevios** [comment] 2023-07-31 06:06
I have determined that Thermal Foundation by itself degrades performance, but the Fast Animated Textures option in OptiFine fixes that. I think the problem is in animated textures and the incompatibility of this function between Nothirium and OptiFine.

**Comment by Meldexun** [comment] 2023-07-31 10:25
Thank you for your help. I will close this then.

For anyone wondering, the incompatibility with the "Smart Animations" setting from Optifine is tracked in #40

**Closed by Meldexun** 2023-07-31 10:25 UTC
Labels: bug, unconfirmed
