### ISSUE TITLE
Strange rendering on supported GL version

### ISSUE THREAD

**Issue by AlexChevios** [Meldexun/Nothirium#79] opened 2023-07-27 18:42 UTC
**Describe the bug**
Rendering works fine only on Nothirium GL 1.5, although version 2.0 is also supported by my GPU.

**Reproducibility**
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Set render type to AUTO/GL4.3/GL4.2/GL2.0
2. See bug
3. Set render type to GL2.0
4. See normal render

**Screenshots/Videos**
[Video](https://youtu.be/JHj2EXhqCIY)

**Versions**
Nothirium: 0.3.2
RenderLib: 1.3.1
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Hardware**
CPU: Intel Core i5 3230M
RAM: 8Gb DDR3L-1600 (Dual Channel)
GPU: Intel HD Graphics 4000
VRAM: 1760Mb

**Log File**
[latest.log](https://gist.github.com/AlexChevios/5f841737cb0a08abe51c91f9624f7d7c)

**Comment by Meldexun** [comment] 2023-07-28 16:06
Duplicate of #74

**Closed by Meldexun** 2023-07-28 16:06 UTC
Labels: bug, unconfirmed
