### ISSUE TITLE
Nothirium causes invisible wall in Compact Machine

### ISSUE THREAD

**Issue by Studumb** [Meldexun/Nothirium#95] opened 2024-04-27 12:03 UTC
**Describe the bug**
Nothirium causes invisible wall in Compact Machine

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Get a Personal Shrinking Device and a Compact Machine
2. Place down the Compact Machine, hold the Personal Shrinking Device and right click the machine
Note: Use from 7x7x7 Compact Machine

**Screenshots/Videos**
Without Nothirium
https://imgur.com/Hq5hL96
With Nothirium
https://imgur.com/ZbYbfi7
**Versions**
Nothirium: 0.3.4 - beta
RenderLib: 1.3.4
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods: Compact Machine - ver 3.0.18

**Hardware**
CPU: i5 - 5200U 2.20 Ghz
RAM: 4 GB
GPU 0: Intel(R) HD Graphics 5500
VRAM: 2 GB
GPU 1: AMD Radeon R7 M265
VRAM: 2 GB

**Log File**
https://gist.github.com/Studumb/bff34ca91d9823ad9b1655caa2ea86d6

**Comment by bloody-scythe** [comment] 2024-06-04 17:29
Had the same problem, a shame really

**Comment by Meldexun** [comment] 2024-06-12 17:57
Duplicate of #63

**Closed by Meldexun** 2024-06-12 17:57 UTC
Labels: bug, unconfirmed
